<a href="https://colab.research.google.com/github/NiroNithy/Personal_Portfolio/blob/Research/HNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q google_play_scraper
!pip install -q transformers
!pip install -q plotly-express

In [ ]:
!pip install PyYAML

Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (6.0.2)

In [ ]:
import pandas as pd
import numpy as np
from google_play_scraper import app, Sort, reviews_all
import plotly_express as px

In [ ]:
HNB_project = reviews_all('com.hnb.DigitalApp', sleep_milliseconds=0, lang='en', sort = Sort.NEWEST)

In [ ]:
df = pd.json_normalize(HNB_project)

In [ ]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,265ef3d1-09b8-4e83-949d-07fedc75a519,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Love,5,0,None,2025-01-29 09:37:18,None,NaT,None
1,de75e8d9-0c32-4566-84c8-1c7bf9634263,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Highly recommended ❤️ very helful app ❤️❤️,5,0,6.5.2,2025-01-27 10:45:15,None,NaT,6.5.2
2,7e7d586d-009d-4ca8-bf53-5d1841184365,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Best banking app,5,0,6.5.2,2025-01-26 12:05:49,None,NaT,6.5.2
3,7445ac62-2872-4b62-9e70-3c0583fa2d4a,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Simple & good app,5,0,None,2025-01-25 15:21:03,None,NaT,None
4,33e0dc1b-94e4-48d1-bdbb-3d9fe0962344,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Very nice Digital Banking app Thank you!,5,0,None,2025-01-25 02:36:11,None,NaT,None

In [ ]:
columns_to_drop = ["reviewId", "userName", "userImage", "score", "thumbsUpCount", "reviewCreatedVersion", "replyContent","repliedAt"]
df = df.drop(columns=columns_to_drop)

In [ ]:
df.head()

                                      content                  at appVersion
0                                        Love 2025-01-29 09:37:18       None
1  Highly recommended ❤️ very helful app ❤️❤️ 2025-01-27 10:45:15      6.5.2
2                            Best banking app 2025-01-26 12:05:49      6.5.2
3                           Simple & good app 2025-01-25 15:21:03       None
4    Very nice Digital Banking app Thank you! 2025-01-25 02:36:11       None

In [ ]:
comment_count_by_appversion = df.groupby('appVersion').size().reset_index(name='Total Comments')

In [ ]:
comment_count_by_appversion = comment_count_by_appversion.sort_values(by='Total Comments', ascending=False)

In [ ]:
print(comment_count_by_appversion)

   appVersion  Total Comments
13      4.5.0             322
4       3.2.0             310
3       3.0.0             303
6       3.7.0             292
5       3.3.0             244
12      4.3.2             177
2       2.7.0             169
10      4.2.0             156
7       4.0.0             119
17      5.3.0              78
19      6.3.0              76
15      4.6.2              60
8       4.1.0              55
0       2.0.0              45
11      4.2.1              43
1       2.2.0              41
16      5.0.0              40
14     4.5.21              37
20      6.3.1              31
21      6.5.2              22
9       4.1.1              19
18      6.2.0              16

In [ ]:
# Define the list of app versions to filter
desired_versions = ["6.5.2", "3.0.0", "3.7.0", "4.3.2", "4.5.0", "4.6.2", "5.0.0", "5.3.0", "6.2.0", "6.3.0", "6.3.1"]

# Filter the DataFrame to keep only rows with the desired appVersion
filtered_df = df[df['appVersion'].isin(desired_versions)]

# Display the filtered DataFrame
filtered_df.head()

,content,at,appVersion
1,Highly recommended ❤️ very helful app ❤️❤️,2025-01-27 10:45:15,6.5.2
2,Best banking app,2025-01-26 12:05:49,6.5.2
5,எப்ப பாரு ஒழுங்கா வேல செய்யுது இல்ல அடிக்கடி m...,2025-01-24 02:13:16,6.5.2
6,Nice,2025-01-24 00:11:44,6.5.2
9,There's nothing wrong with saying that.,2025-01-20 17:53:53,6.5.2

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=filtered_df)

https://docs.google.com/spreadsheets/d/1dyDMDlgJ10RD9oizMhd_gpz-gBisZk_tv6fHLeYnP94#gid=0

In [ ]:
df['at'] = pd.to_datetime(df['at'])

In [ ]:
df['year'] = df['at'].dt.year
comment_counts = df.groupby(['appVersion', 'year']).size().reset_index(name='comment_count')
filtered_comments = comment_counts[comment_counts['year'].isin([2024, 2025])]
filtered_comments = filtered_comments.sort_values(by=['year', 'appVersion'], ascending=[False, True])
print(filtered_comments)

   appVersion  year  comment_count
41      6.5.2  2025             10
10      3.0.0  2024              1
18      3.7.0  2024              1
28      4.3.2  2024              4
30      4.5.0  2024              1
33      4.6.2  2024              2
35      5.0.0  2024             11
36      5.3.0  2024             78
37      6.2.0  2024             16
38      6.3.0  2024             76
39      6.3.1  2024             31
40      6.5.2  2024             12