<a href="https://colab.research.google.com/github/NiroNithy/Personal_Portfolio/blob/Research/MyDataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q google_play_scraper #Scraping Reviews
!pip install -q transformers #Sentiment
!pip install -q plotly-express #Data Visualization

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.1 MB/s eta 0:00:00

In [ ]:
!pip install PyYAML

Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (6.0.2)

In [ ]:
import pandas as pd
import numpy as np
from google_play_scraper import app, Sort, reviews_all
import plotly_express as px

In [ ]:
boc_project = reviews_all('com.ofss.fcdb.mobile.android.phone.boc.launcher', sleep_milliseconds=0, lang='en', sort = Sort.NEWEST)

In [ ]:
#boc_project

In [ ]:
df = pd.json_normalize(boc_project)

In [ ]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,e6a8950b-4d25-45e6-9790-6c1d90a4830b,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,It's time to do the Revamp 😴,1,0,1.2.27,2024-12-01 17:38:26,None,NaT,1.2.27
1,ae2f4b63-7272-449f-bf1d-9eac04345f96,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Their servers are always down at night. What a...,1,0,None,2024-12-01 10:43:37,None,NaT,None
2,06645131-ad13-465b-ac4a-b508242fd41d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Bad UX experience and Bad UI,1,0,1.2.27,2024-11-30 09:53:50,None,NaT,1.2.27
3,095d7379-61b2-4aef-99dd-caca2198ac61,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,The worst app I ever used,1,0,1.2.27,2024-11-30 03:47:02,None,NaT,1.2.27
4,04e010dd-dcd4-4a33-9a8a-846b855db453,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,This app needs a revision soon. All other comp...,1,0,1.2.27,2024-11-29 03:49:26,None,NaT,1.2.27

In [ ]:
columns_to_drop = ["reviewId", "userName", "userImage", "score", "thumbsUpCount", "reviewCreatedVersion", "replyContent","repliedAt"]
df = df.drop(columns=columns_to_drop)

In [ ]:
df.head()

,content,at,appVersion
0,It's time to do the Revamp 😴,2024-12-01 17:38:26,1.2.27
1,Their servers are always down at night. What a...,2024-12-01 10:43:37,None
2,Bad UX experience and Bad UI,2024-11-30 09:53:50,1.2.27
3,The worst app I ever used,2024-11-30 03:47:02,1.2.27
4,This app needs a revision soon. All other comp...,2024-11-29 03:49:26,1.2.27

In [ ]:
filtered_df = df[df["appVersion"] == "1.2.27"]

In [ ]:
filtered_df.head()

,content,at,appVersion
0,It's time to do the Revamp 😴,2024-12-01 17:38:26,1.2.27
2,Bad UX experience and Bad UI,2024-11-30 09:53:50,1.2.27
3,The worst app I ever used,2024-11-30 03:47:02,1.2.27
4,This app needs a revision soon. All other comp...,2024-11-29 03:49:26,1.2.27
8,Worst banking app ever. Not user friendly at a...,2024-11-25 23:17:11,1.2.27

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=filtered_df)

https://docs.google.com/spreadsheets/d/18rYPwCItbp8nETC4AbG5c2D9RvsoQ2DUVhAKq7ooq9o#gid=0

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1aElgLL5UyUX5ZBt3w6-xpZNcDXqcbDhUGXKemfSr0Mc#gid=0

NameError: name 'df' is not defined