<a href="https://colab.research.google.com/github/NiroNithy/Personal_Portfolio/blob/Research/People's_Bank_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q google_play_scraper
!pip install -q transformers
!pip install -q plotly-express

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 684.9 kB/s eta 0:00:00

In [ ]:
!pip install PyYAML

Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (6.0.2)

In [ ]:
import pandas as pd
import numpy as np
from google_play_scraper import app, Sort, reviews_all
import plotly_express as px

In [ ]:
Peoples_project = reviews_all('com.peoplesbank.retailbanking', sleep_milliseconds=0, lang='en', sort = Sort.NEWEST)

In [ ]:
df = pd.json_normalize(Peoples_project)

In [ ]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,068484d1-eff0-47c4-9f40-7d3f8b291fdb,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"After the recent update, I can't use the app. ...",1,0,V 1.36.1.2,2025-01-25 06:58:49,None,NaT,V 1.36.1.2
1,0db055f6-1cee-4d23-ac36-29fa7dcf867a,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,"Shows me a message after the latest update. ""T...",1,1,V 1.36.1.2,2025-01-25 06:12:57,None,NaT,V 1.36.1.2
2,364f4a8d-0cda-4e67-8d66-2232fcb837d7,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Not opening without finger print. My phone is ...,1,1,V 1.36.1.2,2025-01-25 03:05:31,None,NaT,V 1.36.1.2
3,12996e2b-2d34-469b-a70c-a17b7136c969,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,I updated this app on 25 th January 2025. Afte...,1,1,V 1.36.1.2,2025-01-25 01:09:05,None,NaT,V 1.36.1.2
4,6cbb18d9-fe7f-498b-ab7c-cf03f5390a29,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Every time Unable connect server what's this 😡...,1,0,V 1.34.1.2,2025-01-23 12:39:13,"Dear Sir/Madam, We apologize for the inconveni...",2025-01-20 13:27:16,V 1.34.1.2

In [ ]:
columns_to_drop = ["reviewId", "userName", "userImage", "score", "thumbsUpCount", "reviewCreatedVersion", "replyContent","repliedAt"]
df = df.drop(columns=columns_to_drop)

In [ ]:
df.head()

,content,at,appVersion
0,"After the recent update, I can't use the app. ...",2025-01-25 06:58:49,V 1.36.1.2
1,"Shows me a message after the latest update. ""T...",2025-01-25 06:12:57,V 1.36.1.2
2,Not opening without finger print. My phone is ...,2025-01-25 03:05:31,V 1.36.1.2
3,I updated this app on 25 th January 2025. Afte...,2025-01-25 01:09:05,V 1.36.1.2
4,Every time Unable connect server what's this 😡...,2025-01-23 12:39:13,V 1.34.1.2

In [ ]:
# Define the list of app versions to filter
desired_versions = ["V 1.34.1.2", "V 1.36.1.2", "V 1.26.1.2", "V 1.29.1.2", "V 1.32.1.2"]

# Filter the DataFrame to keep only rows with the desired appVersion
filtered_df = df[df['appVersion'].isin(desired_versions)]

# Display the filtered DataFrame
filtered_df.head()

,content,at,appVersion
0,"After the recent update, I can't use the app. ...",2025-01-25 06:58:49,V 1.36.1.2
1,"Shows me a message after the latest update. ""T...",2025-01-25 06:12:57,V 1.36.1.2
2,Not opening without finger print. My phone is ...,2025-01-25 03:05:31,V 1.36.1.2
3,I updated this app on 25 th January 2025. Afte...,2025-01-25 01:09:05,V 1.36.1.2
4,Every time Unable connect server what's this 😡...,2025-01-23 12:39:13,V 1.34.1.2

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=filtered_df)

https://docs.google.com/spreadsheets/d/1odOE5q_zeDXSn4iY-Kbhuktk3xGkYmCO1Bb-fPTF4oo#gid=0

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=filtered_df)

https://docs.google.com/spreadsheets/d/1GOQxpylOEG00OqgSie-k83Und6Nwgl_T8_w5YmFUqgo#gid=0

In [ ]:
#df['at'] = pd.to_datetime(df['at'])

In [ ]:
#df['year'] = df['at'].dt.year

In [ ]:
#comment_counts = df.groupby(['appVersion', 'year']).size().reset_index(name='comment_count')

In [ ]:
#filtered_comments = comment_counts[comment_counts['year'].isin([2024, 2025])]

In [ ]:
#filtered_comments = filtered_comments.sort_values(by=['year', 'appVersion'], ascending=[False, True])

In [ ]:
#print(filtered_comments)

    appVersion  year  comment_count
68  V 1.34.1.2  2025             13
69  V 1.36.1.2  2025              4
11  V 1.10.0.2  2024              1
20  V 1.12.0.2  2024              3
38  V 1.18.1.2  2024              1
41  V 1.19.1.2  2024              1
55  V 1.24.1.2  2024              1
58  V 1.25.1.2  2024              1
61  V 1.26.1.2  2024             19
64  V 1.29.1.2  2024             43
66  V 1.32.1.2  2024             13
67  V 1.34.1.2  2024            130

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=filtered_df)

https://docs.google.com/spreadsheets/d/1-4pKjFEpj5lS2bgDDl3X_o8Dc5w7aZT7hHWQr4gq-F8#gid=0

In [ ]:
comment_count_by_appversion = df.groupby('appVersion').size().reset_index(name='Total Comments')

In [ ]:
comment_count_by_appversion = comment_count_by_appversion.sort_values(by='Total Comments', ascending=False)

In [ ]:
print(comment_count_by_appversion)

      appVersion  Total Comments
5     V 1.12.0.2             566
6     V 1.13.0.2             462
8     V 1.16.1.2             335
4     V 1.11.0.2             322
17    V 1.23.1.2             297
0      V 1.0.0.2             290
31     V 1.9.0.2             276
3     V 1.10.0.2             258
19    V 1.25.1.2             257
18    V 1.24.1.2             224
20    V 1.26.1.2             217
7     V 1.15.1.2             208
30     V 1.8.0.2             193
9     V 1.17.3.2             192
11    V 1.19.1.2             151
25    V 1.34.1.2             141
27     V 1.5.1.2             134
2      V 1.1.0.2             123
10    V 1.18.1.2             120
12     V 1.2.6.2              90
23     V 1.3.5.2              90
29     V 1.7.0.2              63
22    V 1.29.1.2              62
15    V 1.21.1.2              57
14    V 1.20.2.2              56
16    V 1.22.1.2              51
26     V 1.4.1.2              36
28     V 1.6.6.2              27
13    V 1.20.1.2              16
24    V 1.32.1.2              13
1   V 1.0.1306.1               3
21    V 1.28.1.2               1